{
 "title": "Qb",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "categories",
    "label": "Categories",
    "query": {
     "query": "label_values(qbittorrent_torrents_count, category)"
    }
   },
   { "name": "data_source", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Bittorrent network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_connected - qbittorrent_firewalled",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "DHT nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbittorrent_dht_nodes", "legendFormat": "DHT nodes" }
   ]
  },
  {
   "title": "Total downloaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (app) (qbittorrent_alltime_dl_total)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total uploaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (app) (qbittorrent_alltime_ul_total)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Session downloaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (app) (qbittorrent_dl_info_data_total)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Session uploaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (app) (qbittorrent_up_info_data_total)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_dl_info_data_total[2m])"
    }
   ]
  },
  {
   "title": "Qbittorrent Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "qbittorrent_up" }
   ]
  },
  {
   "title": "Total ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by (app) (qbittorrent_alltime_ul_total)) / (sum by (app) (qbittorrent_alltime_dl_total))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Session ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by (app) (qbittorrent_up_info_data_total)) / (sum by (app) (qbittorrent_dl_info_data_total))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_up_info_data_total[2m])"
    }
   ]
  },
  {
   "title": "Transfer Rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(qbittorrent_dl_info_data_total[2m])",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(qbittorrent_up_info_data_total[2m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Torrents by status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qbittorrent_torrents_count{category=~\"${categories}\", status!=\"complete\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Torrents by categories",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(qbittorrent_torrents_count{category=~\"${categories}\",status!=\"complete\"}) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qbittorrent_total_peer_connections_total)",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Average time queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qbittorrent_average_time_queue_total)",
     "legendFormat": "Time queue"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "yaxes": [
    { "format": "dectbytes" }
   ],
   "targets": [
    {
     "expr": "(qbittorrent_free_space_on_disk_total)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Write/Read cache overload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(qbittorrent_write_cache_overload_total[1m])*10",
     "legendFormat": "Write"
    },
    {
     "expr": "rate(qbittorrent_read_cache_overload_total[1m])*10",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Queued io jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(qbittorrent_queued_io_jobs_total)",
     "legendFormat": "Jobs"
    }
   ]
  },
  {
   "title": "Internet traffic per hour $device",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 36 },
   "yaxes": [
    { "format": "bytes", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"192.168.1.58:9100\",device=\"eth0\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"192.168.1.58:9100\",device=~\"eth0\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "contextId": "sensors.fan",
     "nodes": [
      "f653f384-677c-405e-8bfd-c66ee8c2f2ac"
     ],
     "roomId": "b07dbb9f-f5c4-408c-afe1-cf8078674428",
     "spaceId": "2037393c-06ce-43f2-bbbf-b182bef71e9c"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"192.168.1.58:9100\",mode=\"system\"}[2m])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"192.168.1.58:9100\",mode=\"user\"}[2m])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"192.168.1.58:9100\",mode=\"iowait\"}[2m])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"192.168.1.58:9100\",mode=\"idle\"}[2m])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "contextId": "sensors.temperature",
     "nodes": [
      "f653f384-677c-405e-8bfd-c66ee8c2f2ac"
     ],
     "roomId": "b07dbb9f-f5c4-408c-afe1-cf8078674428",
     "spaceId": "2037393c-06ce-43f2-bbbf-b182bef71e9c"
    }
   ]
  }
 ]
}